### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by powder-river** [powder-river/what-to-watch#2]
- [ ] Blank slate
  - [ ] Create a GitHub repo called `what-to-watch`
  - [ ] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [ ] Normal mode
  - [ ] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [ ] Create relevant classes
  - [ ] Write test code for your classes
  - [ ] Load movie data using `csv` module
  - [ ] Write a program to recommend popular movies
  - [ ] Write a function to find similar users
  - [ ] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [ ] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!
